spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/products
server:
  port: 8111
#  error:
#    include-stacktrace: always
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

